name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
        
    - name: Unittests
      run: |
        pytest tests/unittests -v

    - name: MyPy
      run: |
        mypy --config-file=./mypy.ini aedttest/aedt_test_runner.py
