# This workflow will be triggered when new TAG is pushed.
# It will update pyproject.toml file with tag name, build and publish a package to PyPi

name: Upload Python Package

on:
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install .[deploy]

    - name: Validate version in tag
        run: |
          ! [[ ${{ github.ref_name }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$|^[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$ ]] && exit 1

    - name: Set version
      run: |
          sed -i -r "s/version = (.*)/version = \"${{ github.ref_name }}\"/g" pyproject.toml

    - name: Build package
      run: python -m flit build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
