name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - uses: pre-commit/action@v2.0.3
