name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
          python-version: '2.7'
    - run: |
          python -m pip install --upgrade pip==20.2.4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - uses: pre-commit/action@v2.0.3
