name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install virtualenv
      run: |
        python -m pip install -U virtualenv==20.10.0
    - uses: pre-commit/action@v2.0.3
