name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

# Install venv to avoid issues https://github.com/pre-commit/action/issues/135
    - name: Install virtualenv
      run: |
        python -m pip install -U virtualenv==20.10.0
    - uses: pre-commit/action@v2.0.3
